//! Pins the text of every proof format's `to_string` / `to_string_repr`.
//!
//! The expected strings cover every step variant and every optional part
//! (empty and non-empty clauses, premises and arguments, several items in a
//! list, negative and extreme DRAT literals). Each string-producing method is
//! also checked against the bytes its streaming `write` counterpart emits, so
//! the two renderings cannot drift apart.

use oxiz_proof::alethe::{AletheProof, AletheRule};
use oxiz_proof::coq::export_theory_to_coq;
use oxiz_proof::drat::DratProof;
use oxiz_proof::lfsc::{LfscProof, LfscSort, LfscTerm};
use oxiz_proof::proof::Proof;
use oxiz_proof::theory::{TheoryProof, TheoryRule};

fn utf8(bytes: Vec<u8>) -> String {
    match String::from_utf8(bytes) {
        Ok(text) => text,
        Err(e) => panic!("writer emitted non-UTF-8 bytes: {e}"),
    }
}

#[test]
fn alethe_text_is_pinned() {
    let mut proof = AletheProof::new();
    let a = proof.assume("(= a b)");
    let b = proof.assume("(not (= a b))");
    let c = proof.step(
        vec!["(= a b)".into(), "(not (= a b))".into()],
        AletheRule::Resolution,
        vec![a, b],
        vec!["x".into(), "1".into()],
    );
    proof.step_simple(Vec::new(), AletheRule::Refl);
    proof.step(
        vec!["c".into()],
        AletheRule::Trans,
        vec![c],
        vec!["y".into()],
    );
    proof.anchor(Vec::new());
    proof.anchor(vec![
        ("x".to_string(), "Int".to_string()),
        ("y".to_string(), "Bool".to_string()),
    ]);
    proof.define_fun("f", Vec::new(), "Int", "0");
    proof.define_fun(
        "g",
        vec![
            ("u".to_string(), "Int".to_string()),
            ("v".to_string(), "Real".to_string()),
        ],
        "Bool",
        "(< u v)",
    );

    let expected = "; Alethe proof generated by OxiZ\n\
                    \n\
                    (assume t1 (= a b))\n\
                    (assume t2 (not (= a b)))\n\
                    (step t3 (cl (= a b) (not (= a b))) :rule resolution :premises (t1 t2) :args (x 1))\n\
                    (step t4 (cl) :rule refl)\n\
                    (step t5 (cl c) :rule trans :premises (t3) :args (y))\n\
                    (anchor :step t6)\n\
                    (anchor :step t7 :args ((x Int) (y Bool)))\n\
                    (define-fun f () Int 0)\n\
                    (define-fun g ((u Int) (v Real)) Bool (< u v))\n";
    assert_eq!(proof.to_string(), expected);

    let mut written = Vec::new();
    assert!(proof.write(&mut written).is_ok());
    assert_eq!(utf8(written), expected);

    assert_eq!(
        AletheProof::new().to_string(),
        "; Alethe proof generated by OxiZ\n\n"
    );
}

#[test]
fn drat_text_is_pinned() {
    let mut proof = DratProof::new();
    proof.add_clause(vec![1, -2, 3]);
    proof.delete_clause(vec![-1]);
    proof.add_clause(Vec::new());
    proof.delete_clause(Vec::new());
    proof.add_clause(vec![i32::MIN, 7, i32::MAX]);

    let expected = "1 -2 3 0\nd -1 0\n0\nd 0\n-2147483648 7 2147483647 0\n";
    assert_eq!(proof.to_string(), expected);

    let mut written = Vec::new();
    assert!(proof.write_text(&mut written).is_ok());
    assert_eq!(utf8(written), expected);

    // A binary-format proof still renders its text form.
    let mut binary = DratProof::binary();
    binary.add_clause(vec![-4, 5]);
    assert_eq!(binary.to_string(), "-4 5 0\n");

    assert_eq!(DratProof::new().to_string(), "");
}

#[test]
fn lfsc_text_matches_its_writer() {
    let mut proof = LfscProof::new();
    proof.declare_sort("S", 0);
    proof.declare_sort("F", 2);
    proof.declare_const("c", LfscSort::Int);
    proof.define("one", LfscSort::Int, LfscTerm::IntLit(1));
    proof.check(LfscTerm::App(
        "f".to_string(),
        vec![LfscTerm::Var("c".to_string()), LfscTerm::True],
    ));

    let text = proof.to_string();
    let mut written = Vec::new();
    assert!(proof.write(&mut written).is_ok());
    assert_eq!(text, utf8(written));
    assert!(text.starts_with("; LFSC proof generated by OxiZ\n\n(declare S type)\n"));
    assert_eq!(text.lines().count(), 2 + 5);

    assert_eq!(
        LfscProof::new().to_string(),
        "; LFSC proof generated by OxiZ\n\n"
    );
}

#[test]
fn proof_text_is_pinned() {
    let mut proof = Proof::new();
    let a = proof.add_axiom("(p)");
    let b = proof.add_axiom("(q)");
    let c = proof.add_inference("and_intro", vec![a, b], "(and p q)");
    proof.add_inference_with_args("mp", vec![c], vec!["k".to_string(), "2".to_string()], "(r)");
    proof.add_inference("taut", Vec::new(), "(true)");
    proof.add_inference_with_args("inst", vec![a], vec!["t".to_string()], "(s)");

    let expected = "; Proof with 6 nodes\n\
                    \n\
                    p0: (axiom (p))\n\
                    p1: (axiom (q))\n\
                    p2: (and_intro [p0, p1] => (and p q))\n\
                    p3: (mp [p2] :args [k, 2] => (r))\n\
                    p4: (taut [] => (true))\n\
                    p5: (inst [p0] :args [t] => (s))\n";
    assert_eq!(proof.to_string_repr(), expected);

    let mut written = Vec::new();
    assert!(proof.write(&mut written).is_ok());
    assert_eq!(utf8(written), expected);

    assert_eq!(Proof::new().to_string_repr(), "; Proof with 0 nodes\n\n");
}

#[test]
fn theory_text_and_coq_export_are_pinned() {
    let mut proof = TheoryProof::new();
    let a = proof.add_axiom(TheoryRule::Refl, "(= x x)");
    let b = proof.add_step(TheoryRule::Symm, vec![a], "(= x x)");
    proof.add_step_with_args(
        TheoryRule::Trans,
        vec![a, b],
        vec!["x".into(), "y".into()],
        "(= x y)",
    );

    let expected = "; Theory proof generated by OxiZ\n\
                    \n\
                    t0: (= x x) [refl]\n\
                    t1: (= x x) [t0 | symm]\n\
                    t2: (= x y) [t0, t1 | trans x y]\n";
    assert_eq!(proof.to_string_repr(), expected);

    let mut written = Vec::new();
    assert!(proof.write(&mut written).is_ok());
    assert_eq!(utf8(written), expected);

    let coq = export_theory_to_coq(&proof);
    assert!(coq.contains(
        "(* Theory axioms and lemmas *)\n\
         (* Step 0: Refl *)\n\
         Parameter theory_step_0 : Prop.\n\
         (* Step 1: Symm *)\n\
         Parameter theory_step_1 : Prop.\n\
         (* Step 2: Trans *)\n\
         Parameter theory_step_2 : Prop.\n\
         \n\
         (* Theory proof complete *)\n"
    ));
}
